#!/usr/bin/env ruby

INPUT_FILE = "input.txt"
input = File.readlines(INPUT_FILE).map(&:chomp)

coverage = 0

def overlaps(r1, r2)
  r1.cover?(r2.first) || r2.cover?(r1.first)
end

input.each do |line|
  m = line.match /(\d+)-(\d+),(\d+)-(\d+)/

  r1 = (m[1].to_i .. m[2].to_i)
  r2 = (m[3].to_i .. m[4].to_i)

  if overlaps(r1, r2)
    coverage += 1
  end
end

puts "Fully covered ranges: #{coverage}"
