#!/usr/bin/env ruby

INPUT_FILE = "input.txt"
input = File.readlines(INPUT_FILE).map(&:chomp)

# ['a','z','A','Z'].map(&:ord)
# [97, 122, 65, 90]

def priority(char)
  if char.ord > 97
    char.ord - 96
  else
    char.ord - 38
  end
end

def find_same_in(first, second, third)
  first.split("") & second.split("") & third.split("")
end

priorities = 0

# process each 3 lines in a group

group = input.slice!(0, 3)
while (group != nil && group.length == 3)
  same = find_same_in(group[0], group[1], group[2])
  same.each do |ch|
    priorities += priority(ch)
  end

  group = input.slice!(0, 3)
end 

puts "Sum of priorities: #{priorities}"
