#!/usr/bin/env ruby

INPUT_FILE = "input.txt"
input = File.readlines(INPUT_FILE).map(&:chomp)

# key = page
# values = pages that must be after value
rules = {}
updates = []

input.each do |line|
  next if line.empty?
  first,second = line.split "|"

  if second
    page = first.to_i
    rules[page] ||= []
    rules[page] << second.to_i
  else
    updates << first.split(",").map(&:to_i)
  end
end

def fix(update, rules)
  update.sort_by { |page| -(rules[page] & update).length }
end

def right_order?(update, rules)
  fixed = fix(update, rules)
  update == fixed
end

total_correct = 0
total_fixed = 0

updates.each do |update|
  fixed = fix(update, rules)
  if (fixed == update)
    total_correct += update[update.length / 2]
  else
    total_fixed += fixed[fixed.length / 2]
  end
end

puts "Correct updates total: #{total_correct}"
puts "Fixed incorrect updates total: #{total_fixed}"
