#!/usr/bin/env ruby

INPUT_FILE = "input.txt"
input = File.readlines(INPUT_FILE).map(&:chomp)

result = 0

line = input.join

# remove everything between don't and do commands
scrubbed = line.gsub /don\'t\(\).+?do\(\)/, ''
matches = scrubbed.scan /mul\((\d+),(\d+)\)/

matches.each do |m|
  a,b = m
  result += (a.to_i * b.to_i)
end

puts "Result: #{result}"
