#!/usr/bin/env ruby

INPUT_FILE = "input.txt"
input = File.readlines(INPUT_FILE).map(&:chomp)

elfs = []
index = 0

input.each do |entry|
  if entry == nil || entry.length == 0
    index += 1
  else
    cals = entry.to_i
    elfs[index] ||= 0
    elfs[index] += cals
  end
end

puts "Found #{elfs.length} elfs"
maxes = elfs.each_with_index.max(3)

puts "Part 1: top elf"
max = maxes[0]
puts "Elf #{max[1]} has #{max[0]} calories"

puts "Part 2: top 3 elves"
maxes.each do |m|
  puts "Elf #{m[1]} has #{m[0]} calories"
end
total = maxes.map {|m| m[0]}.sum
puts "Total calories: #{total}"
