#!/usr/bin/env ruby

DAYS = 256
LIFECYCLE = 6
SPAWN = 8

input = File.readlines("input.txt")
initial_state = input.first.split(',').map(&:to_i)

# data store for stages: stage => count of fish in that stage
stages = {}

(0..SPAWN).to_a.reverse.each { |i| stages[i] = 0 }

# initialize the stages
initial_state.each { |i| stages[i] += 1 }

puts "Starting with #{stages.values.sum} fish"
# puts stages

(1..DAYS).each do |day|
    # algo:
    # dupe the stages hash
    # move all values down a stage
    # stage 0: add to 6 (lifecycle), add to 8 (spawn)
    # reset the new stages
    new_stages = {}
    (0..SPAWN).to_a.reverse.each { |i| new_stages[i] = 0 }

    stages.keys.sort.reverse.each do |k|
        if k == 0
            new_stages[LIFECYCLE] += stages[k]
            new_stages[SPAWN] = stages[k]
        else
            new_stages[k-1] += stages[k]
        end
    end
    stages = new_stages

    puts "Day #{day}: #{stages.values.sum} fish"
    # puts stages
end