#!/usr/bin/env ruby

INPUT_FILE = "input.txt"
input = File.readlines(INPUT_FILE).map(&:chomp)

THROW_MAP = { 'A' => :rock, 'B' => :paper, 'C' => :scissors }
OUTCOME_MAP = { 'X' => 0, 'Y' => 3, 'Z' => 6 }
SCORES = { rock: 1, paper: 2, scissors: 3 }

def score(opponent, outcome)
  o = THROW_MAP[opponent]
  result = OUTCOME_MAP[outcome]
  o_score = SCORES[o]

  p_score = case result
    when 0
      o_score - 1
    when 3
      o_score
    when 6
      o_score + 1
  end

  if p_score == 0
    p_score = 3
  elsif p_score > 3
    p_score = 1
  end 

  return p_score + result
end

total_score = 0
rounds = 0

input.each do |round|
  opponent, outcome = round.split(' ')
  total_score += score(opponent, outcome)
  rounds += 1
end

puts "Total score after #{rounds} rounds: #{total_score}"
