#!/usr/bin/env ruby

INPUT_FILE = "input.txt"
input = File.readlines(INPUT_FILE).map(&:chomp)

THROW_MAP = { 'A' => :rock, 'X' => :rock, 'B' => :paper, 'Y' => :paper, 'C' => :scissors, 'Z' => :scissors }
SCORES = { rock: 1, paper: 2, scissors: 3 }

def score(opponent, player)
  o = THROW_MAP[opponent]
  p = THROW_MAP[player]
  o_score = SCORES[o]
  p_score = SCORES[p]
  battle = p_score - o_score

  # draw scores
  # anything - anything = 0

  # winning scores
  # 1 - 3 = -2
  # 2 - 1 = 1
  # 3 - 2 = 1

  # losing scores
  # 1 - 2 = -1
  # 2 - 3 = -1
  # 3 - 1 = 2

  if battle == 0
    return p_score + 3 # tie
  elsif battle == -2 || battle == 1
    return p_score + 6 # win
  elsif battle == -1 || battle == 2
    return p_score + 0 # lose
  else
    raise "oops, invalid battle score: #{battle}"
  end
end

total_score = 0
rounds = 0

input.each do |round|
  o,p = round.split(' ')
  total_score += score(o,p)
  rounds += 1
end

puts "Total score after #{rounds} rounds: #{total_score}"
