#!/usr/bin/env ruby

aim = 0
x,y = 0,0

# forward = x+ && y + aim*unit
# down = aim+
# up = aim-

File.foreach("input.txt") do |line|
    m = line.match /(\w+)\s*(\d+)/i
    next unless m
    direction = m[1]
    dist = m[2].to_i
    if direction =~ /forward/
        x += dist
        y += (aim * dist)
    elsif direction =~ /down/
        aim += dist
    elsif direction =~ /up/
        aim -= dist
    end
end

puts "x: #{x}, y: #{y}, mult: #{x*y}"