#!/usr/bin/env ruby

INPUT_FILE = "input.txt"
input = File.readlines(INPUT_FILE).map(&:chomp)

def safe?(list)
  unsafe_count = 0
  direction = nil
  (1...list.length).each do |i|
    # unsafe if direction changes, is zero, or abs(delta) < 1 or > 3
    delta = list[i-1] - list[i]
    if delta == 0 || delta.abs < 1 || delta.abs > 3
      unsafe_count +=1
    end

    if delta != 0
      new_direction = delta / delta.abs
      if direction && new_direction != direction
        unsafe_count += 1
      end
      direction = new_direction
    end
  end

  return unsafe_count <= 1
end

reports = []

input.each do |i|
  reports << i.split.map(&:to_i)
end

safe_count = 0

reports.each do |r|
  if safe?(r)
    safe_count += 1
  end
end

puts "Safe: #{safe_count}"
